#!/usr/bin/env python3
"""Self-check for check_commit_attribution.py.

Every case is built by concatenation so this file carries no trailer of its own — the check reads
commits rather than the tree, but a literal here would still be a line in the repository saying the
thing the repository forbids.

Half of these tests exist because a review found the branch they cover had none: `main`'s exit code
could be mutated to a permanent pass, `commits()` could be given a different separator, and
`resolve_base` could be made to return `HEAD` instead of refusing — all with ten tests still green.
Those branches decide whether the gate can fail at all, so they are exercised against real
repositories built in temporary directories rather than through the pure function alone.

Run with: python3 test_check_commit_attribution.py
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_commit_attribution as check  # noqa: E402
from check_commit_attribution import commits, findings_for, is_assistant_identity, parse_log  # noqa: E402

CO_AUTHOR = "Co-a" + "uthored-by: "
VENDOR = "<noreply@" + "anthropic.com>"
ASSISTANT = "Claude Opus 5 " + VENDOR
SESSION = "Claude-" + "Session: https://claude.ai/code/session_0123456789"
SHA = "0123456789abcdef0123456789abcdef01234567"
HUMAN = "famesjranko <andrewmcdonald42@gmail.com>"


def findings(body: str, *, author: str = HUMAN, committer: str = HUMAN) -> list[str]:
    """Findings for a commit whose subject is fixed and whose body is the case under test."""
    subject = "fix(core): a thing"
    return findings_for(SHA, subject, subject + "\n\n" + body, author, committer)


class AttributionShapeTest(unittest.TestCase):
    def test_assistant_co_author_is_reported(self):
        # Given the trailer Claude Code appends to a commit it wrote
        found = findings(CO_AUTHOR + ASSISTANT + "\n")
        # Then it is reported, naming the commit and quoting the line
        self.assertEqual(len(found), 1)
        self.assertIn(SHA[:7], found[0])
        self.assertIn("co-author", found[0])

    def test_co_author_casing_is_ignored(self):
        # Given the exact casing the incident's commits carried, which differs from the git default
        found = findings("Co-A" + "uthored-By: " + ASSISTANT + "\n")
        # Then it is still reported — the trailer's case is not part of its meaning
        self.assertEqual(len(found), 1)

    def test_session_trailer_is_reported_on_its_own(self):
        # Given a session link with no co-author line beside it
        found = findings(SESSION + "\n")
        # Then the link alone is a finding — it names the tool as plainly as the co-author does
        self.assertEqual(len(found), 1)
        self.assertIn("names the tool", found[0])

    def test_session_trailer_casing_is_ignored(self):
        # Given the same trailer lowercased
        found = findings(SESSION.lower() + "\n")
        # Then it is still reported
        self.assertEqual(len(found), 1)

    def test_generated_with_and_generated_by_are_both_reported(self):
        # Given both wordings in live use — the tool writes one, the PR footer the other
        for footer in (
            "Generated with " + "[Claude Code](https://claude.com/claude-code)",
            "Generated by " + "[Claude Code](https://claude.ai/code/session_x)",
        ):
            with self.subTest(footer=footer):
                # Then each is reported
                self.assertEqual(len(findings(footer + "\n")), 1)

    def test_a_generated_with_line_naming_no_assistant_is_not_reported(self):
        # Given a footer naming an ordinary tool
        body = "Generated with ./gradlew apiDump\n"
        # Then nothing is reported — the phrase alone is not the finding, the tool named is
        self.assertEqual(findings(body), [])

    def test_every_copy_in_a_squash_body_is_reported(self):
        # Given the shape GitHub's squash UI produced: the branch's trailers, then its own copy
        body = CO_AUTHOR + ASSISTANT + "\n" + SESSION + "\n\n---------\n\n" + CO_AUTHOR + ASSISTANT + "\n"
        found = findings(body)
        # Then all three lines are reported, so amending on the first does not hide the rest
        self.assertEqual(len(found), 3)

    def test_bot_co_authors_are_not_reported(self):
        # Given the co-authors this repo's own automation writes
        body = (
            CO_AUTHOR
            + "dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\n"
            + CO_AUTHOR
            + "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>\n"
        )
        # Then nothing is reported — a machine address alone is not an assistant
        self.assertEqual(findings(body), [])

    def test_an_assistant_wearing_a_bot_suffix_is_reported(self):
        # Given a `[bot]` identity that is an assistant rather than repository automation
        found = findings(CO_AUTHOR + "copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>\n")
        # Then it is reported: both halves are present, the name and the machine address
        self.assertEqual(len(found), 1)

    def test_human_co_author_is_not_reported(self):
        # Given an ordinary co-authored commit
        self.assertEqual(findings(CO_AUTHOR + "Andy <andrewmcdonald42@gmail.com>\n"), [])

    def test_a_person_whose_name_matches_is_not_locked_out(self):
        # Given a contributor whose own name is an assistant's, at their own address
        found = findings(CO_AUTHOR + "Claude Dubois <claude.dubois@example.fr>\n")
        # Then nothing is reported — the name alone is not enough, and there is no allowlist to
        # add a real person to
        self.assertEqual(found, [])

    def test_prose_naming_the_tool_is_not_reported(self):
        # Given a body that discusses the assistant rather than crediting it
        body = "Generated with Claude Code, then rewritten by hand before committing.\n"
        # Then nothing is reported: the trailer must be the whole line
        self.assertEqual(findings(body), [])

    def test_an_indented_quotation_of_the_banned_line_is_not_reported(self):
        # Given a commit message quoting the trailer it is removing, indented as a quotation
        body = "The line this commit removes:\n\n    " + CO_AUTHOR + ASSISTANT + "\n"
        # Then nothing is reported — a git trailer sits at column 0, so an indented copy is prose
        self.assertEqual(findings(body), [])

    def test_assistant_as_the_author_is_reported(self):
        # Given the identity a hosted session's container arrives configured with
        found = findings("", author="Claude " + VENDOR)
        # Then it is reported even though the message carries no trailer at all
        self.assertEqual(len(found), 1)
        self.assertIn("authored", found[0])

    def test_assistant_as_the_committer_is_reported(self):
        # Given a human author whose commit was written by an assistant's git identity
        found = findings("", committer="Claude " + VENDOR)
        # Then the committer field is reported on its own
        self.assertEqual(len(found), 1)
        self.assertIn("committed", found[0])

    def test_a_vendor_domain_alone_is_not_an_assistant(self):
        # Given a person with an address at a vendor domain but no assistant in their name
        self.assertFalse(is_assistant_identity("A Person <person@anthropic.com>"))
        # And given an assistant at that domain
        self.assertTrue(is_assistant_identity("Claude <noreply@anthropic.com>"))


class GitRange(unittest.TestCase):
    """The branches that decide whether the gate can fail at all, against real repositories."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.origin = Path(self._tmp.name) / "origin"
        self.origin.mkdir()
        self.git_in("init", "-q", "-b", "main")
        self.git_in("config", "user.name", "Test Person")
        self.git_in("config", "user.email", "person@example.com")
        self.commit("initial commit")
        self.addCleanup(self._tmp.cleanup)

    def git_in(self, *args: str, cwd: Path | None = None) -> str:
        return subprocess.run(["git", *args], cwd=cwd or self.origin, capture_output=True, text=True, check=True).stdout

    def commit(self, message: str, cwd: Path | None = None) -> None:
        root = cwd or self.origin
        (root / "file.txt").write_text(message, encoding="utf-8")
        self.git_in("add", "-A", cwd=root)
        subprocess.run(
            ["git", "commit", "-q", "-F", "-"], cwd=root, input=message, text=True, capture_output=True, check=True
        )

    def in_repo(self, path: Path):
        """Run the check's git calls against `path` for the duration of a `with` block."""
        return _Chdir(path)

    def test_a_message_containing_the_old_record_separator_is_still_read(self):
        # Given a commit whose body holds a raw RS byte before its trailer
        body = "subject\n\nbody with \x1e in it\n\n" + CO_AUTHOR + ASSISTANT + "\n"
        self.commit(body)
        # When the range is read
        with self.in_repo(self.origin):
            found = [f for c in commits("HEAD~1", "HEAD") for f in findings_for(*c)]
        # Then the trailer after the separator is still reported, rather than silently truncated
        self.assertEqual(len(found), 1)

    def test_an_empty_message_body_does_not_break_parsing(self):
        # Given a commit whose message is a bare subject
        self.commit("just a subject")
        # When the range is read
        with self.in_repo(self.origin):
            parsed = commits("HEAD~1", "HEAD")
        # Then it parses as one commit with all five fields
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0][1], "just a subject")

    def test_a_record_with_missing_fields_refuses(self):
        # Given a log record that does not hold five fields, as a truncated read would produce
        with self.assertRaises(SystemExit) as raised:
            parse_log("deadbeef\x00only a subject\x00an author\x00")
        # Then it refuses — a dropped record is a commit the check silently did not read
        self.assertIn("cannot parse", str(raised.exception))

    def test_each_commit_in_a_range_is_attributed_to_its_own_sha(self):
        # Given three commits, only the middle one carrying a trailer
        self.git_in("branch", "base")
        self.commit("first, clean")
        self.commit("second\n\n" + CO_AUTHOR + ASSISTANT + "\n")
        self.commit("third, clean")
        # When the range is read
        with self.in_repo(self.origin):
            parsed = commits("base", "HEAD")
            found = [f for c in parsed for f in findings_for(*c)]
        # Then three separate commits are parsed, and the finding names the one that carries it
        self.assertEqual(len(parsed), 3)
        self.assertEqual(len(found), 1)
        middle = next(c for c in parsed if c[1] == "second")
        self.assertIn(middle[0][:7], found[0])

    def test_an_empty_range_parses_as_no_commits(self):
        # Given a range with nothing in it
        with self.in_repo(self.origin):
            # Then it is empty rather than a parse error
            self.assertEqual(commits("HEAD", "HEAD"), [])

    def test_main_returns_one_when_a_finding_exists(self):
        # Given a repository whose branch adds a commit carrying a trailer
        self.git_in("branch", "base")
        self.commit("subject\n\n" + CO_AUTHOR + ASSISTANT + "\n")
        # When the check runs over it
        with self.in_repo(self.origin):
            code = main_with_argv(["--base", "base"])
        # Then it exits non-zero — the branch that makes this gate able to fail at all
        self.assertEqual(code, 1)

    def test_main_returns_zero_on_a_clean_range(self):
        # Given a branch whose commits carry nothing
        self.git_in("branch", "base")
        self.commit("an honest commit")
        # When the check runs over it
        with self.in_repo(self.origin):
            code = main_with_argv(["--base", "base"])
        # Then it exits zero
        self.assertEqual(code, 0)

    def test_a_shallow_clone_fails_rather_than_reading_nothing(self):
        # Given a shallow clone of a repository whose tip carries a trailer
        self.commit("subject\n\n" + CO_AUTHOR + ASSISTANT + "\n")
        shallow = Path(self._tmp.name) / "shallow"
        subprocess.run(
            ["git", "clone", "-q", "--depth", "1", f"file://{self.origin}", str(shallow)],
            capture_output=True,
            check=True,
        )
        # When the check runs there
        # Then it refuses, rather than resolving origin/main to an empty range and passing
        with self.in_repo(shallow), self.assertRaises(SystemExit) as raised:
            main_with_argv([])
        self.assertIn("shallow", str(raised.exception))

    def test_a_push_build_reads_the_commit_it_landed(self):
        # Given the commit a push replaced, as GitHub reports it
        self.git_in("branch", "before")
        before = self.git_in("rev-parse", "before").strip()
        self.commit("subject\n\n" + CO_AUTHOR + ASSISTANT + "\n")
        # When the check runs with that SHA in the environment and no base branch to fall back on
        with self.in_repo(self.origin), _Env(MUSICMETA_PUSH_BEFORE=before, GITHUB_BASE_REF=""):
            code = main_with_argv([])
        # Then the pushed commit is read and reported, rather than falling to an empty range
        self.assertEqual(code, 1)

    def test_a_pull_request_is_measured_against_its_own_base(self):
        # Given a stacked branch whose parent branch already carries a trailer
        self.git_in("branch", "parent")
        self.git_in("checkout", "-q", "parent")
        self.commit("subject\n\n" + CO_AUTHOR + ASSISTANT + "\n")
        self.git_in("checkout", "-q", "-b", "child")
        self.commit("an honest commit")
        self.git_in("update-ref", "refs/remotes/origin/parent", "parent")
        # When the check runs with the PR's base branch named
        with self.in_repo(self.origin), _Env(GITHUB_BASE_REF="parent", MUSICMETA_PUSH_BEFORE=""):
            code = main_with_argv([])
        # Then only the child's own commit is read, so it is not red for its parent's history
        self.assertEqual(code, 0)

    def test_an_unresolvable_explicit_base_refuses(self):
        # Given a --base that names nothing
        with self.in_repo(self.origin), self.assertRaises(SystemExit) as raised:
            main_with_argv(["--base", "no-such-ref"])
        # Then it refuses rather than falling back to a base that would read a different range
        self.assertIn("no-such-ref", str(raised.exception))


class _Chdir:
    def __init__(self, path: Path):
        self.path = path

    def __enter__(self):
        self.previous = Path.cwd()
        os.chdir(self.path)

    def __exit__(self, *exc):
        os.chdir(self.previous)


class _Env:
    """Set environment variables for a block; an empty value removes the variable."""

    def __init__(self, **values: str):
        self.values = values

    def __enter__(self):
        self.previous = {key: os.environ.get(key) for key in self.values}
        for key, value in self.values.items():
            os.environ[key] = value if value else ""
            if not value:
                os.environ.pop(key, None)

    def __exit__(self, *exc):
        for key, value in self.previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


def main_with_argv(argv: list[str]) -> int:
    """Call the check's main() with a given argv, restoring sys.argv afterwards."""
    previous = sys.argv
    sys.argv = ["check_commit_attribution.py", *argv]
    try:
        return check.main()
    finally:
        sys.argv = previous


if __name__ == "__main__":
    unittest.main()
